Makefile: fix config.h leaking to the next build when using CONFIG_UPDATE_IMAGE.
When we build a first image with the fallback/ prefix,
  with the CONFIG_MAINBOARD_DO_NATIVE_VGA_INIT option,
  and without CONFIG_UPDATE_IMAGE, the image builds fine,
  and build/coreboot.rom is generated.

Then if when we run "make menuconfig" and select CONFIG_UPDATE_IMAGE
  along with different options( here we will unselect
  the CONFIG_MAINBOARD_DO_NATIVE_VGA_INIT ), we then have
  a build failure like that:
    build/generated/coreboot_ram.o: In function `gma_func0_init':
    [...]/src/northbridge/intel/i945/gma.c:62: undefined reference to `i915lightup'
    build/generated/coreboot_ram.o: In function `lb_framebuffer':
    [...]/src/lib/coreboot_table.c:176: undefined reference to `vbe_mode_info_valid'
    [...]/src/lib/coreboot_table.c:182: undefined reference to `fill_lb_framebuffer'
    collect2: error: ld returned 1 exit status
  despite of having #if CONFIG_MAINBOARD_DO_NATIVE_VGA_INIT
  and #endif surrounding the usage of i915lightup
  in [...]/src/northbridge/intel/i945/gma.c
  It is due to the fact that build/config.h has
  #define CONFIG_MAINBOARD_DO_NATIVE_VGA_INIT 0
  in it, despite of having selected CONFIG_MAINBOARD_DO_NATIVE_VGA_INIT
  only in the first build(the one with the /fallback prefix).

Change-Id: I345c2359876918eba1019f25d86d1392f4ee85e1
Signed-off-by: Denis 'GNUtoo' Carikli <GNUtoo@no-log.org>