intel/cougar_canyon2/romstage.c: Remove `cbmemc_reinit`
Enabling CBMEM console for the Cougar Canyon 2 the build fails.

	src/mainboard/intel/cougar_canyon2/romstage.c: In function 'romstage_main_continue':
	src/mainboard/intel/cougar_canyon2/romstage.c:345:2: error: implicit declaration of function 'cbmemc_reinit' [-Werror=implicit-function-declaration]
	cc1: all warnings being treated as errors

Since commit cbf5bdfe6 (CBMEM: Always select CAR_MIGRATION) [1] calling
`cbmemc_reinit()` in the board’s romstage is not needed anymore, so remove it.

[1] http://review.coreboot.org/3916

Change-Id: I4dff2d11f073e2829ab3b081b5460f66eead4640
Signed-off-by: Paul Menzel <paulepanter@users.sourceforge.net>