mb/google/brya: Add missing parameter name to variant_generate_s0ix_hook
Fixes the following build error:

src/mainboard/google/brya/mainboard.c: In function 'variant_generate_s0ix_hook':
src/mainboard/google/brya/mainboard.c:157:40: error: parameter name omitted
 void __weak variant_generate_s0ix_hook(enum s0ix_entry)
                                        ^~~~~~~~~~~~~~~

BUG=None
TEST=`abuild -a -x -c max -p none -t google/brya` now succeeds

Change-Id: Id578766e2a3b7647e920740dde3e356a7db39d4d
Signed-off-by: Reka Norman <rekanorman@chromium.org>
Reviewed-on: https://review.coreboot.org/c/coreboot/+/63564
Tested-by: build bot (Jenkins) <no-reply@coreboot.org>
Reviewed-by: Eric Lai <eric_lai@quanta.corp-partner.google.com>