util/cbfstool: Use `%zu` instead of `%ld` for size_t arguments
Since commit aa2f739a (cbfs: fix issues with word size and endianness.) [1]
cbfstool cannot be built anymore under 32-bit platforms.

	error: format ‘%ld’ expects argument of type ‘long int’, but argument 3 has type ‘size_t’

For arguments of size_t the conversion specifier `%zu` should to be used
instead of `%ld` as sizes are non-negative.

[1] http://review.coreboot.org/4817

Change-Id: Id84a20fbf237376a31f7e4816bd139463800c977
Signed-off-by: Paul Menzel <paulepanter@users.sourceforge.net>