cbmem: Makefile: Add compilation rule
Commit »cbmem compilation needs to use the hardened toolchain«
(7c6b6bb5) [1] introduced `CPPFLAGS` but used `CFLAGS`, which might
give the following build error, which was not spotted by Jenkins.

    cbmem.c:36:34: fatal error: boot/coreboot_tables.h: Datei oder Verzeichnis nicht gefunden
    compilation terminated.

Looks like the default compilation rule does not always include
`CPPFLAGS`. Therefore, add a more complete compilation rule.

[1] http://review.coreboot.org/1791

Change-Id: I254d76c7d98b6f920501407239566e9655b2ddeb
Signed-off-by: Paul Menzel <paulepanter@users.sourceforge.net>
Signed-off-by: Nico Huber <nico.huber@secunet.com>