3rdparty/vboot: Update submodule pointer to upstream master
Building depthcharge master currently fails as depthcharge commit 74ca8ae5
(depthcharge: Hide dev mode timeout description) changed the function signature
according to vboot commit 59fd331b (vboot/ui: pass timer_disabled to
vb2ex_display_ui()), which is not yet present in the vboot checkout:

    $ make
    […]
        CC         drivers/ec/vboot_auxfw.depthcharge.o
    src/drivers/ec/vboot_auxfw.c: In function 'display_firmware_sync_screen':
    src/drivers/ec/vboot_auxfw.c:117:5: error: too many arguments to function 'vb2ex_display_ui'
         vb2ex_display_ui(VB2_SCREEN_FIRMWARE_SYNC,
         ^~~~~~~~~~~~~~~~
    In file included from /dev/shm/coreboot-1/3rdparty/vboot/firmware/include/vb2_api.h:18,
                     from src/drivers/ec/vboot_auxfw.c:17:
    /dev/shm/coreboot-1/3rdparty/vboot/firmware/include/../2lib/include/2api.h:1262:13: note: declared here
     vb2_error_t vb2ex_display_ui(enum vb2_screen screen,
                 ^~~~~~~~~~~~~~~~

So update the submodule pointer from commit 68de90c7 (Allow building for
non-CrOS environments) to commit ed23c084 (Reset EC when transitioning to dev
mode).

This brings in 7 new commits.

Change-Id: Icd5408fb824fc5da470774b7f493b916dff17832
Signed-off-by: Paul Menzel <pmenzel@molgen.mpg.de>
Reviewed-on: https://review.coreboot.org/c/coreboot/+/43517
Tested-by: build bot (Jenkins) <no-reply@coreboot.org>
Reviewed-by: Yu-Ping Wu <yupingso@google.com>
Reviewed-by: Joel Kitching <kitching@google.com>