UPSTREAM: src/lib: Use tabs instead of spaces
Fix the following errors and warnings detected by checkpatch.pl:

ERROR: code indent should use tabs where possible
ERROR: switch and case should be at the same indent
WARNING: Statements should start on a tabstop
WARNING: please, no spaces at the start of a line
WARNING: please, no space before tabs
WARNING: suspect code indent for conditional statements
WARNING: labels should not be indented

TEST=Build and run on Galileo Gen2

Change-Id: Id17a59b48fcb5ddce232eb63cf86e04f13278bdb
Signed-off-by: Patrick Georgi <pgeorgi@chromium.org>
Original-Commit-Id: e20a3191f58ffb37da3ed6414491d61dbfc7e583
Original-Change-Id: Iebcff26ad41ab6eb0027b871a1c06f3b52dd207c
Original-Signed-off-by: Lee Leahy <Leroy.P.Leahy@intel.com>
Original-Reviewed-on: https://review.coreboot.org/18732
Original-Tested-by: build bot (Jenkins)
Original-Reviewed-by: Martin Roth <martinroth@google.com>
Reviewed-on: https://chromium-review.googlesource.com/453377