cbmem: map_memory: Use length modifier `l` for an argument with type off_t
cbmem currently fails to build due to `-Werror` and the following warning.

    $ make
    cc -O2 -Wall -Werror -iquote ../../src/include -iquote ../../src/src/arch/x86  -c -o cbmem.o cbmem.c
    cbmem.c: In function ‘map_memory’:
    cbmem.c:87:2: error: format ‘%zx’ expects argument of type ‘size_t’, but argument 2 has type ‘off_t’ [-Werror=format]
    […]

Using the length modifier `l` instead of `z` for an argument with type off_t,
so `%lx` instead of `%lz`, gets rid of this warning.

Change-Id: I1360abbc47aa1662e1edfbe337cf7911695c532f
Signed-off-by: Paul Menzel <paulepanter@users.sourceforge.net>