commonlib: Remove unused static function.
Building with Clang without option -Wno-unused-function causes building
error. I don't know why GCC doesn't have that issue.

------------
coreboot/src/commonlib/fsp1_1_relocate.c:47:23: error:
 unused function 'le8toh' [-Werror,-Wunused-function]
static inline uint8_t le8toh(uint8_t byte)
                      ^
1 error generated.
------------

Change-Id: Iecd1e84e4321446412ef68d65dc918baf1ab45ce
Signed-off-by: Zheng Bao <fishbaozi@gmail.com>
Reviewed-on: http://review.coreboot.org/12339
Tested-by: build bot (Jenkins)
Reviewed-by: Paul Menzel <paulepanter@users.sourceforge.net>
Reviewed-by: Aaron Durbin <adurbin@chromium.org>
Reviewed-by: York Yang <york.yang@intel.com>