cbmem: Makefile: Fix typo: s,CPPFLAGS,CFLAGS,
Commit »cbmem compilation needs to use the hardened toolchain«
(7c6b6bb5) [1] introduced `CPPFLAGS` but used `CFLAGS`, which gives
the following build error, which was not spotted by Jenkins,
because programs under `utils/` are not build tested.

    cbmem.c:36:34: fatal error: boot/coreboot_tables.h: Datei oder Verzeichnis nicht gefunden
    compilation terminated.

As this is a C program, change `CPPFLAGS` to `CFLAGS`, causing the
actual directories get passed to the compiler and the header file
is found then.

[1] http://review.coreboot.org/1791

Change-Id: I254d76c7d98b6f920501407239566e9655b2ddeb
Signed-off-by: Paul Menzel <paulepanter@users.sourceforge.net>