Makefile.inc: Only add `-Wno-unused-but-set-variable` for GCC
Clang (3.5) does not know that option.

	error: unknown warning option '-Wno-unused-but-set-variable'; did you mean '-Wno-unused-const-variable'? [-Werror,-Wunknown-warning-option]

Fix up commit f69a99db (coreboot: x86: enable gc-sections) to only add
that option, when GCC is used.

Change-Id: I65b41133a806df1803ccc445e27184c579a718a0
Signed-off-by: Paul Menzel <paulepanter@users.sourceforge.net>
Reviewed-on: http://review.coreboot.org/9377
Tested-by: build bot (Jenkins)
Reviewed-by: Aaron Durbin <adurbin@google.com>