northbridge/intel/i945/raminit.c: Remove set but unused variable `reg16`
Removing `-Wno-unused-but-set-variable` from `CFLAGS` results in the
following error.

	    CC         northbridge/intel/i945/raminit.romstage.o
	src/northbridge/intel/i945/raminit.c: In function 'sdram_detect_cas_latency_and_ram_speed':
	src/northbridge/intel/i945/raminit.c:497:6: error: variable 'lowest_common_cas' set but not used [-Werror=unused-but-set-variable]
	src/northbridge/intel/i945/raminit.c: In function 'sdram_program_pll_settings':
	src/northbridge/intel/i945/raminit.c:1955:15: error: variable 'reg16' set but not used [-Werror=unused-but-set-variable]
	cc1: all warnings being treated as errors

The variable is declared as `volatile`, but as it is not read anywhere
it can be removed.

Change-Id: Id4a758644a7b799e7662113c07d395e053525934
Signed-off-by: Paul Menzel <paulepanter@users.sourceforge.net>