intel/lynxpoint/usb_debug.c: Only build `enable_usbdebug()` in `PRE_RAM`
Building the board Intel White Tip Mountain which has the Intel
Lynx Point platform controller hub (PCH) and enabling the USB
debug console, the build fails with the following error.

    $ LANG=C make
    […]
        CC         southbridge/intel/lynxpoint/usb_debug.ramstage.o
    /src/southbridge/intel/lynxpoint/usb_debug.c: In function 'enable_usbdebug':
    /src/southbridge/intel/lynxpoint/usb_debug.c:35:2: error: unknown type name 'device_t'
    /src/southbridge/intel/lynxpoint/usb_debug.c:35:2: error: implicit declaration of function 'PCI_DEV' [-Werror=implicit-function-declaration]
    /src/southbridge/intel/lynxpoint/usb_debug.c:38:2: error: implicit declaration of function 'pci_write_config32' [-Werror=implicit-function-declaration]
    /src/southbridge/intel/lynxpoint/usb_debug.c:41:2: error: implicit declaration of function 'pci_write_config8' [-Werror=implicit-function-declaration]
    cc1: all warnings being treated as errors
    make: *** [build/southbridge/intel/lynxpoint/usb_debug.ramstage.o] Error 1

Guarding the function `enable_usbdebug()` with

    ifdef __PRE_RAM__

the build of Intel White Tip Mountain succeeds.

Change-Id: I1bc7965bb422110595840bba7d3dec2a30a8a7f6
Signed-off-by: Paul Menzel <paulepanter@users.sourceforge.net>