ASRock E350M1: Add `dimmSpd.h` with declaration of `AmdMemoryReadSPD`
The warning

    […]
        CC         mainboard/asrock/e350m1/BiosCallOuts.ramstage.o
    src/mainboard/asrock/e350m1/BiosCallOuts.c: In function 'BiosReadSpd':
    src/mainboard/asrock/e350m1/BiosCallOuts.c:424:3: warning: implicit declaration of function 'AmdMemoryReadSPD' [-Wimplicit-function-declaration]
    […]

is present since merging the ASRock E350M1 port. Though this
could only be verified with commit
“bypass the "Do not use global variables in romstage"” (52ffb2b6).

Commit »Add the AMD Torpedo mainboard« (770b8777) added the header
file `dimmSpd.h` which was integrated for AMD Persimmon in commit
»Persimmon updates for AMD F14 rev C0« (d7a696d0). Copying this
header file to the ASRock E350M1 and adding that to `BioCallOuts.c`
fixes the GCC warning.

Note that currently the `dimmSpd.h` header file could also be used
in `dimmSpd.c`, which uses the function `AmdMemoryReadSPD` too, but
declares it in the file. This is not changed, as currently it does
not cause a warning and SPD functions will be moved to the
Fam14 AGESA wrapper code [1]. The ASRock E350M1 code will be
adapted to use that code then.

[1] http://review.coreboot.org/#/c/2497/

Change-Id: I4cdb1c5633561864a9d729918d1d1bcd8dbce18e
Signed-off-by: Paul Menzel <paulepanter@users.sourceforge.net>