cpu/amd/model_fxx/powernow_acpi.c: Remove set but unused variable `Start_vid`
Removing `-Wno-unused-but-set-variable` from `CFLAGS` the build for the
ASRock 939A785GMH fails with the following error.

	    CC         cpu/amd/model_fxx/powernow_acpi.ramstage.o
	src/cpu/amd/model_fxx/powernow_acpi.c: In function 'pstates_algorithm':
	src/cpu/amd/model_fxx/powernow_acpi.c:761:25: error: variable 'Start_vid' set but not used [-Werror=unused-but-set-variable]
	cc1: all warnings being treated as errors

When adding support for PSS object generation for AMD pre Family Fh CPUs
(199c694f) the function `pstates_algorithm` was copied and adapted, but
`Start_vid` is not needed anymore as a static table is used. So remove
the variable `Start_vid`.

Change-Id: I3002951d168cade6461941c16d78373c47792e13
Signed-off-by: Paul Menzel <paulepanter@users.sourceforge.net>