util/cbfstool: Use `%zu` instead of `%ld` for size_t arguments
Since commit aa2f739a (cbfs: fix issues with word size and endianness.) [1]
cbfstool fails to built under 32-bit platforms.

	error: format ‘%ld’ expects argument of type ‘long int’, but argument 3 has type ‘size_t’

Some of these errors were fixed indirectly by subsequent patches, but not
all of them.

Also no error is seen when building a coreboot image which indirectly
builds cbfstool at `build/cbfstool` too.

For arguments of size_t the length modifier `z` and, as sizes are
non-negative, the conversion specifier `u` should be used, so use `%zu`
instead of `%ld` as the format string.

[1] http://review.coreboot.org/4817

Change-Id: Id84a20fbf237376a31f7e4816bd139463800c977
Signed-off-by: Paul Menzel <paulepanter@users.sourceforge.net>