intel/lynxpoint/Makefile.inc: Add `usb_debug.c` to fix build error
Building the board Intel White Tip Mountain which has the Intel
Lynx Point platform controller hub (PCH) and enabling the USB
debug console, the build fails with the following error.

    $ LANG=C make
    […]
        CC         vendorcode/google/chromeos/fmap.smm.o
    build/cpu/x86/smm/smm.o: In function `usbdebug_init':
    /src/coreboot/src/lib/usbdebug.c:559: undefined reference to `set_debug_port'
    /src/coreboot/src/lib/usbdebug.c:564: undefined reference to `set_debug_port'
    make: *** [build/cpu/x86/smm/smm.elf] Error 1

Adding `usb_debug.c` to the build, so it is available when building
ramstage and SMM, fixes this error, though building Intel White Tip
Mountain succeeds only with the next commit.

Change-Id: If52eef38935dd52a8598c8272e5a03c748556fb3
Signed-off-by: Kyösti Mälkki <kyosti.malkki@gmail.com>
Signed-off-by: Paul Menzel <paulepanter@users.sourceforge.net>