southbridge/via/vt8237r/ctrl.c: Remove unused variable `regm3`
A FIXME was added but never discussed.

Remove it as I see no downside.

    CC         southbridge/via/vt8237r/ctrl.ramstage.o
src/southbridge/via/vt8237r/ctrl.c: In function 'vt8237_cfg':
src/southbridge/via/vt8237r/ctrl.c:32:11: error: variable 'regm3' set but not used [-Werror=unused-but-set-variable]
cc1: all warnings being treated as errors

Change-Id: I6bb652419a54b7b7190e417346581f38335425ae
Signed-off-by: Paul Menzel <paulepanter@users.sourceforge.net>