treewide: Remove unused #includes of spi_winbond.h
We want to add some function declarations as static_testable to this
header but including it in a .c file outside of tests will yield a gcc
warning like:

    error: 'function' declared 'static' but never defined
      [-Werror=unused-function]

It seems these includes aren't necessary anyways so we just remove
them.

Change-Id: I17147136579140b94728ceb1c369b1348714bc53
Signed-off-by: Daniel Gröber <dxld@darkboxed.org>
Reviewed-on: https://review.coreboot.org/c/coreboot/+/44090
Tested-by: build bot (Jenkins) <no-reply@coreboot.org>
Reviewed-by: Frans Hendriks <fhendriks@eltan.com>
Reviewed-by: HAOUAS Elyes <ehaouas@noos.fr>