sb/intel/ibexpeak/Makefile.mk: Add shared ramstage ../bd82x6x/cfr.c
Recent addition of a shared Intel ME CFR setup menu for bd82x6x did not
take into account that ibexpeak ME also relies on that code. There for
currently building the Lenovo ThinkPad X201 with CFR menu fails with:

"undefined reference to `sb_cfr_set_string'"

See commit 6f581f48084a ("sb/intel/bd82x6x: Add CFR menu for Intel ME")

By including '../bd82x6x/cfr.c' in ramstage guarded by a CFR option it
is possible to build a working CFR menu based Lenovo ThinkPad X201 port
although testing on real hardware shows that the ME CFR setup options
are not effective yet. Fixing that still needs to be investigated.

Change-Id: I33643fcb10b6d1d8406ef2d8ea072194e43df265
Signed-off-by: Walter Sonius <walterav1984@gmail.com>
Reviewed-on: https://review.coreboot.org/c/coreboot/+/95383
Reviewed-by: Patrick Rudolph <patrick.rudolph@9elements.com>
Tested-by: build bot (Jenkins) <no-reply@coreboot.org>