soc/amd: smbus: Use correct type for uintptr_t
Fix the format warning below by using `PRIxPTR`, which is defined as
unsigned long.

    src/soc/amd/common/block/smbus/smbus.c:33:56: error: format specifies type 'size_t' (aka 'unsigned int') but the argument has type 'uintptr_t' (aka 'unsigned long') [-Werror,-Wformat]
                    printk(BIOS_ERR, "Invalid SMBus or ASF base %#zx\n", mmio);
                                                                ~~~~     ^~~~
                                                                %#lx
    src/include/console/console.h:60:61: note: expanded from macro 'printk'
    #define printk(LEVEL, fmt, args...) do_printk(LEVEL, fmt, ##args)
                                                         ~~~    ^~~~
    1 error generated.

Change-Id: I727c490d3097dcf36cdbcd4db2852cd49d11785f
Signed-off-by: Paul Menzel <pmenzel@molgen.mpg.de>
Reviewed-on: https://review.coreboot.org/c/coreboot/+/51843
Tested-by: build bot (Jenkins) <no-reply@coreboot.org>
Reviewed-by: Felix Held <felix-coreboot@felixheld.de>