northbridge/intel/haswell/gma.c: Guard `graphics_base` by `MAINBOARD_DO_NATIVE_INIT`
Removing `-Wno-unused-but-set-variable` from `CFLAGS` results in the
following error.

	    CC         northbridge/intel/haswell/gma.ramstage.o
	src/northbridge/intel/haswell/gma.c: In function 'gma_func0_init':
	src/northbridge/intel/haswell/gma.c:281:6: error: variable 'graphics_base' set but not used [-Werror=unused-but-set-variable]
	cc1: all warnings being treated as errors

The variable `graphics_base` is only used when the Kconfig variable
`MAINBOARD_DO_NATIVE_INIT` is selected, so guard its declaration and
assignment with preprocessor macros.

Change-Id: Id667d9a747a0931bebe951861bc96e1043715848
Signed-off-by: Paul Menzel <paulepanter@users.sourceforge.net>