southbridge/via/vt8237r/ctrl.c: Remove set but unused variable `regm3`
Removing `-Wno-unused-but-set-variable` from `CFLAGS` results in the
following error.

	    CC         southbridge/via/vt8237r/ctrl.ramstage.o
	src/southbridge/via/vt8237r/ctrl.c: In function 'vt8237_cfg':
	src/southbridge/via/vt8237r/ctrl.c:32:11: error: variable 'regm3' set but not used [-Werror=unused-but-set-variable]
	cc1: all warnings being treated as errors

There is already a `FIXME` line regarding this issue, added in commit
»remove more warnings.« (3c8ac786).

Looking at the history, the file `vt8237_ctrl.c` was based on
`k8t890_ctrl.c`, but removed the code needing the variable `regm3` and
was not adapted in that place.

Therefore remove the variable `regm3` and use `regm` which should also
shadow page E correctly now.

Change-Id: I6bb652419a54b7b7190e417346581f38335425ae
Signed-off-by: Paul Menzel <paulepanter@users.sourceforge.net>