cpu/samsung/exynos5250/cpu.c: Remove unused variable `ret`
	    CC         cpu/samsung/exynos5250/cpu.ramstage.o
	src/cpu/samsung/exynos5250/cpu.c: In function 'exynos_displayport_init':
	src/cpu/samsung/exynos5250/cpu.c:88:6: error: variable 'ret' set but not used [-Werror=unused-but-set-variable]
	cc1: all warnings being treated as errors

Change-Id: I72a5a802aef0a75b0277eaac6ca6c24793812d98
Signed-off-by: Paul Menzel <paulepanter@users.sourceforge.net>