Lenovo X60: Make it compile with CONFIG_DYNAMIC_CBMEM=y
Note that while the code in src/mainboard/lenovo/x60
  compiles, it still doesn't fix the i945/raminit.c code
  which fails like that:
  i945/raminit.c:31:21: error: no previous prototype for 'get_cbmem_toc' [-Werror=missing-prototypes]
  and may have more failures(since I cound't compile coreboot fully).

Change-Id: I8c6fbce07b86cb8ca112d5c10cf892ef05955bbc
Signed-off-by: Denis 'GNUtoo' Carikli <GNUtoo@no-log.org>