google/parrot/smihandler.c: Use `battery_critical_logged` only with `ELOG_GSMI`
Removing `-Wno-unused-but-set-variable` from `CFLAGS` results in the
following error.

	    CC         mainboard/google/parrot/smihandler.smm.o
	src/mainboard/google/parrot/smihandler.c: In function 'mainboard_smi_ec':
	src/mainboard/google/parrot/smihandler.c:97:13: error: variable 'battery_critical_logged' set but not used [-Werror=unused-but-set-variable]
	cc1: all warnings being treated as errors

As the variable is only used, when the Kconfig variable `ELOG_GSMI` is
not zero, only declare and set it in that case.

Change-Id: I2ef291d2f3e7d35545014e03ba8e0045da6050e5
Signed-off-by: Paul Menzel <paulepanter@users.sourceforge.net>