util/smmstoretool/Makefile: Add missing includes
The compilation of the tool fails under the
coreboot-sdk:2025-10-19_4a3cc37cbd with the error:

In file included from util/cbfstool/flashmap/kv_pair.c:6:
util/cbfstool/flashmap/kv_pair.h: In function 'kv_pair_fmt':
util/cbfstool/flashmap/kv_pair.h:81:36:
  error: expected declaration specifiers before '__printf'
   81 |                                    __printf(3, 4);
      |                                    ^~~~~~~~

Including the missing compiler definitions from src/commonlib
fixes the issue.

Change-Id: I6aa274ab44f8381ee4bd7a3ef7ee8b6cf62b2cb6
Signed-off-by: Michał Żygowski <michal.zygowski@3mdeb.com>
Reviewed-on: https://review.coreboot.org/c/coreboot/+/92058
Reviewed-by: Sergii Dmytruk <sergii.dmytruk@3mdeb.com>
Tested-by: build bot (Jenkins) <no-reply@coreboot.org>